name: $(Rev:.r)

variables:


pool:
  name: Hosted Ubuntu 1604

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*[Tt]ests/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- powershell: './SetVersion.ps1'
  displayName: 'Set Package Version'

- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: custom
    custom: pack
    projects: 'Music.Core/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactStagingDirectory) -p:VersionPrefix=$(VersionPrefix) -p:VersionSuffix=$(VersionSuffix) -p:FileVersion=$(VersionFile) -p:ProductVersion=$(VersionProduct)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: NuGetCommand@2
  displayName: 'Push to MyGet'
  inputs:
    command: 'push'
    packagesToPush: '$(build.artifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'MyGet'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
